version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION%
after_build:
- dotnet pack -c %CONFIGURATION% --no-build
test:
  assemblies:
    only:
    - '**\*.Tests.Core.dll'
cache:
- '%USERPROFILE%\.nuget\packages'