version: 2.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
before_build:
- appveyor-retry dotnet restore -v Minimal
build:
  parallel: true
  verbosity: normal
after_build:
- dotnet pack -c %CONFIGURATION% --no-build
test:
  assemblies:
    only:
    - '*.Tests.*'