version: 2.1.{build}
image: Visual Studio 2022
configuration:
- Debug
- Release
before_build:
- cmd: appveyor-retry dotnet restore -v Minimal
build:
  parallel: true
  verbosity: normal
after_build:
- cmd: dotnet pack -c %CONFIGURATION% --no-build
test:
  assemblies:
    only:
    - '*.Tests.*'