version: 2.1.{build}
image: Visual Studio 2022
configuration:
- Debug
- Release
environment:
  TransientFaultHandlingTestDatabase: Server=(local)\SQL2019;User ID=sa;Password=Password12!;Database=TransientFaultHandlingTestDatabase
  TransientFaultHandlingTestServer: Server=(local)\SQL2019;User ID=sa;Password=Password12!
before_build:
- cmd: >-
    appveyor-retry dotnet restore -v Minimal

    net start MSSQL$SQL2019
build:
  parallel: true
  verbosity: normal
after_build:
- cmd: dotnet pack -c %CONFIGURATION% --no-build
test:
  assemblies:
    only:
    - '*.Tests.*'